TARGET_URL: 'https://www.jiji.com'
TARGET_LIST_PATH: '/jc/list?g=pol'
USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36'